Table Notes {
  ID integer [PK, increment]
  User bigint [not null]
  Date bigint [not null]
  Note text [not null]
  Severity varchar(8) [not null]
  ChannelID bigint
  MessageID bigint
  Noter bigint [not null]
  INDEXES {
   User [name: 'user_index'] 
  }
}